#Open up your pod definition for later reference
#kubernetes.io/docs/concepts/workloads/controllers/deployment
#Copy-paste the template and edit


apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels: #Copy-paste name & app from metadata->labels
      name: worker-app-pod
      app: demo-voting-app
  template: #everything from metadata and spec of redis-pod.yml
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app #One container per pod, so we only have 1 image. We can have multiple but rarely.
          image: dockersamples/examplevotingapp_worker #from dockerHub

#Once you are good, you can delete your pod yml but i choose to keep.